### PR TITLE
I dont really like generated kernel header

### PR DESCRIPTION
**Pull request by peaktogooo**

### CODE REVIEW

**Comment by peaktogooo** [comment]
@peaktogoo Should fix the build abort due to kernel header...

**Comment by anayw2001** [comment]
@peaktogoo why would you do this ._.

**Comment by peaktogooo** [comment]
@anayw2001 it's for GSI branch dude

**Comment by peaktogooo** [comment]
@peaktogoo @rc42Ohead Told me to make an pull request, and i did told him to make a9-gsi branch. Just want to make aquaris more gsi friendly

**Comment by anayw2001** [comment]
lineage manages fine, what was the error?

**Comment by peaktogooo** [comment]
@anayw2001 lol you don't build for gsi. do you even know what is gsi

**Comment by peaktogooo** [comment]
i'll just wait rc to merge it

**Comment by anayw2001** [comment]
TIL you need to build something to know what an acronym stands for.

**Comment by peaktogooo** [comment]
@anayw2001 I want to merge my changes to the branch a9-gsi. Nothing conflict with another branch. I even did for cryptfs_hw today

**Pull request closed without merging**
